---
title: "hw3"
author: "Gregory Matesi"
output: 
    pdf_document :
      latex_engine : xelatex
---

# Problem 1

The *Urkiola* data set in the spatstat package contains locations of birch and oak trees in secondary wood in Urkiola Natural Park. They are part of a ore extensive dataset collected and analyzed by Laskurain (2008). They coordinates of the trees are given in metersf. Let the "oak" trees be the cases and "birch" trees be the controls.

## Part a

*Perform a test to determine whether the most unusual window of case/control event locations in the study area can be considered a cluster using the spatial scan statistic under the random labaling hypothesisf. Use $n_{sim}=499$ randomly labeled data sets and $\alpha=0.10$. Make sure to clearly describe your nul and alternative hypothesis. Make your conclusion in the context of the problem.

```{r}

```

## Part b

Using your analysis from the previous problem, create a plot of the case/control event locations, the associated study area boundary, and a legend indicating the cases/controls. Add the window identifying the most unusual window of case/control event locations (according to the spatial scan statistic) and any potential secondary clusters. Comment on the results.

## Part c

Perform a test for clustering using the $q$ nearest neighbors method. Use $q=3,5,...,19$ and $n_{sim}=499$ randomly labeled data sets. For which $q$ are there more cases than we would expect under random labeling in the $q$ locations nearest each case? At what scale does this clustering appear to occur (use the contrasts)?