---
title: "splancs"
output: html_document
---

It seems like csr() is the splancs equivalent of spatstat.core::runifpoint. And it seems like khat() is the splancs equivalent to spatstat.core::Lest.

```{r eval=FALSE}
?spatstat.core::runifpoint
?splancs::csr

?spatstat.core:Lest
?splancs::khat

?polygon
```

```{r}
library(splancs)
data("cardiff")
str(cardiff)
class(cardiff)
```

```{r}
data(grave, package = "smacpod")
str(grave)
str(grave$window)
str(grave$window$bdry)
bdry_list <- grave$window$bdry[[1]]

my.poly <- cbind(bdry_list$x, bdry_list$y)
```

```{r}
?cardiff
plot(cardiff$x, cardiff$y)
polygon(my.poly)
```

```{r}
x <- grave$x
y <- grave$y

pts <- cbind(x,y)
```

Plot the estimated L function for the observed data
```{r}
s = seq(0, 5200, len = 512)
#envelopes <- Kenv.csr(nptg=grave$n, poly=my.poly, nsim, s)
lower <- envelopes$lower
upper <- envelopes$upper


plot(s, sqrt(khat(pts, my.poly, s)/pi)-s,
     type = "l", 
     xlab = "splans - polygon boundary", ylab = "estimated L",
     ylim= c(-400, 600) )
legend("topleft",
       legend = c("min/max",
                  "2.5th, 97.5th percentiles",
                  "median"),
       lty = c(2, 1, 4))
lines(s, sqrt(upper/pi)-s, lty = 2)
lines(s, sqrt(lower/pi)-s, lty = 2)

```



```{r}
s = seq(0, 5200, len = 512)     # Spatial scales ranging from 0 to 5000
nsim <- 200                     # Number of simulation to do at each spatial scale
level <- 0.95

# For each spatial scale, for each simulation, use csr() to get new points in the poly.
# Take the quantile/min/max over nsim simulation for each spatial scale s.

# Call csr() inside khat() like this. remove NAs when plotting or when calculating the quantile/min/max.
quant.kenv.csr <- function (nptg, poly, nsim, s, quiet = FALSE) 
{
    kmax <- rep(0, length = length(s))
    kmin <- rep(1e+34, length = length(s))
    for (isim in (1:nsim)) {
        if (!quiet) 
            cat("Doing simulation ", isim, "\n")
        khsim <- khat(csr(poly, nptg), poly, s)
        kmax <- pmax(kmax, khsim)
        kmin <- pmin(kmin, khsim)
    }
    list(lower = kmin, upper = kmax)
}
```

