---
title: "DenverMedicalCare"
author: "Gregory Matesi"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library(sf)
library(spdep)
# library(maptools) # For readShapePoints
library(smerc)


```

# Data
```{r}
rm(list = ls())
file.path <- "~../../Desktop/SpatialStatisticsClass/Project/Delayed_Medical_Care_in_Adults_($)_-_CDPHE_Community_Level_Estimates_(Census_Tracts)/Delayed_Medical_Care_in_Adults_(%24)_-_CDPHE_Community_Level_Estimates_(Census_Tracts)."
chc <- sf::st_read(paste0(file.path, "shp"))
counties <- c("Denver",
               "Arapahoe",
               "Adams",
               "Jefferson",
              "Douglas",
              "Elbert",
              "Broomfield"
              # "Clear Creek",
              # "Gilpin",
              # "Park",
              # "Weld"
              )
denver <- chc[which(chc$County_Nam %in% counties & 
                 !is.na(chc$DelayedMC_)),]
colorado <- chc[which(!is.na(chc$DelayedMC_)),]
which(chc$County_Nam %in% counties & is.na(chc$DelayedMC_))
length(which(chc$County_Nam %in% counties & is.na(chc$DelayedMC_)))
chc$County_Nam[which(chc$County_Nam %in% counties & is.na(chc$DelayedMC_))]
```
# Plots
```{r}
colorado_nb <- poly2nb(st_geometry(colorado))
denver_nb <- poly2nb(st_geometry(denver))

plot(st_geometry(denver), border="grey60")
plot(denver_nb, coords = st_centroid(st_geometry(denver)),
     add=TRUE, col="blue", pch = 19, cex = 0.6)
plot(st_centroid(st_geometry(denver)), add=TRUE)

plot(st_geometry(chc), border="grey60")
plot(colorado_nb, coords = st_centroid(st_geometry(colorado)),
     add=TRUE, col="blue", pch = 19, cex = 0.6)
plot(st_centroid(st_geometry(colorado)), add=TRUE)

denver$observed <- (denver$Adult_Popu * denver$DelayedMC_ * .01)
plot(denver[,c(14,13)])

colorado$observed <- (colorado$Adult_Popu * colorado$DelayedMC_ * .01)
plot(colorado[,c(14,13)])
```

```{r}
denver.coords <- st_coordinates(st_centroid(st_geometry(denver)))
colorado.coords <- st_coordinates(st_centroid(st_geometry(colorado)))

summary(denver$Adult_Popu)
summary(denver$observed)

summary(colorado$Adult_Popu)
summary(colorado$observed)
```


# Beseg Newell
```{r}
cstars <- c(200, 250, 275)

denver.bn1 = bn.test(coords = denver.coords,
              cases = denver$observed,
              pop = denver$Adult_Popu,
              cstar = cstars[1],
              alpha = 0.01)
denver.bn2 = bn.test(coords = denver.coords,
              cases = denver$observed,
              pop = denver$Adult_Popu,
              cstar = cstars[2],
              alpha = 0.01)
denver.bn3 = bn.test(coords = denver.coords,
              cases = denver$observed,
              pop = denver$Adult_Popu,
              cstar = cstars[3],
              alpha = 0.01)

summary(denver.bn1)

summary(denver.bn2)
summary(denver.bn3)


library(RColorBrewer) # useful for determining plotting colors
# look at qualitative color mapping that is colorblind friendly
display.brewer.all(type = "qual", colorblindFriendly = TRUE)
mycol = brewer.pal(3, "Dark2")
# create vector of colors to show results
# default is white (no clustering)
dncol = rep("white", nrow(denver))
length(mycol) == 3

# the most likely cluster locations are lightorange for cstar = 6
dncol[denver.bn1$clusters[[1]]$locids] = mycol[1]
# the most likely cluster locations are lightgreen for cstar = 17
dncol[denver.bn2$clusters[[1]]$locids] = mycol[2]
# the most likely cluster locations are magenta for cstar = 6, 17
dncol[denver.bn3$clusters[[1]]$locids] = mycol[3]


# plot most likely clusters
plot(st_geometry(denver), border="grey60", axes = TRUE, col = dncol)
legend("topright",
       legend = c("Cluster k = 1", "Cluster k = 2",
                  "Cluster k = 3"),
       lwd = 10, col = mycol)

cstars <- c(200, 300, 400)


colorado.bn1 = bn.test(coords = colorado.coords,
              cases = colorado$observed,
              pop = colorado$Adult_Popu,
              cstar = cstars[1],
              alpha = 0.01)
colorado.bn2 = bn.test(coords = colorado.coords,
              cases = colorado$observed,
              pop = colorado$Adult_Popu,
              cstar = cstars[2],
              alpha = 0.01)
colorado.bn3 = bn.test(coords = colorado.coords,
              cases = colorado$observed,
              pop = colorado$Adult_Popu,
              cstar = cstars[3],
              alpha = 0.01)

summary(colorado.bn1)

summary(colorado.bn2)
summary(colorado.bn3)


library(RColorBrewer) # useful for determining plotting colors
# look at qualitative color mapping that is colorblind friendly
display.brewer.all(type = "qual", colorblindFriendly = TRUE)
mycol = brewer.pal(3, "Dark2")
# create vector of colors to show results
# default is white (no clustering)
dncol = rep("white", nrow(colorado))
length(mycol) == 3

# the most likely cluster locations are lightorange for cstar = 6
dncol[colorado.bn1$clusters[[1]]$locids] = mycol[1]
# the most likely cluster locations are lightgreen for cstar = 17
dncol[colorado.bn2$clusters[[1]]$locids] = mycol[2]
# the most likely cluster locations are magenta for cstar = 6, 17
dncol[colorado.bn3$clusters[[1]]$locids] = mycol[3]


# plot most likely clusters
plot(st_geometry(colorado), border="grey60", axes = TRUE, col = dncol)
legend("topright",
       legend = c("Cluster k = 1", "Cluster k = 2",
                  "Cluster k = 3"),
       lwd = 10, col = mycol)
```

# CEPP Denver
```{r}
nstars <- c(9000, 20000, 50000)
summary(denver$Adult_Popu)
denver.cepp1 = cepp.test(coords = denver.coords,
                     cases = denver$observed,
                     pop = denver$Adult_Popu,
                     nstar = nstars[1],
                     alpha = 0.01)

denver.cepp2 = cepp.test(coords = denver.coords,
                     cases = denver$observed,
                     pop = denver$Adult_Popu,
                     nstar = nstars[2],
                     alpha = 0.01)

denver.cepp3 = cepp.test(coords = denver.coords,
                     cases = denver$observed,
                     pop = denver$Adult_Popu,
                     nstar = nstars[3],
                     alpha = 0.01)

# basic info
denver.cepp1
# cluster info
summary(denver.cepp1)
clusters(denver.cepp1)


# basic info
denver.cepp2
# cluster info
summary(denver.cepp2)
clusters(denver.cepp2)


# basic info
denver.cepp3
# cluster info
summary(denver.cepp3)
clusters(denver.cepp3)

plot(sf::st_geometry(denver), border = "grey60", axes = TRUE,
     col = color.clusters(denver.cepp1))
legend("topright", legend = c("n* = 1"))
# basic plot
plot(denver.cepp1)

plot(sf::st_geometry(denver), border = "grey60", axes = TRUE,
     col = color.clusters(denver.cepp2))
legend("topright", legend = c("n* = 2"))
# basic plot
plot(denver.cepp2)

plot(sf::st_geometry(denver), border = "grey60", axes = TRUE,
     col = color.clusters(denver.cepp3))
legend("topright", legend = c("n* = 3"))
# basic plot
plot(denver.cepp3)
```

# CEPP Colorado
```{r}
nstars <- c(12000, 30000, 50000)
summary(colorado$Adult_Popu)
colorado.cepp1 = cepp.test(coords = colorado.coords,
                     cases = colorado$observed,
                     pop = colorado$Adult_Popu,
                     nstar = nstars[1],
                     alpha = 0.01)

colorado.cepp2 = cepp.test(coords = colorado.coords,
                     cases = colorado$observed,
                     pop = colorado$Adult_Popu,
                     nstar = nstars[2],
                     alpha = 0.01)

colorado.cepp3 = cepp.test(coords = colorado.coords,
                     cases = colorado$observed,
                     pop = colorado$Adult_Popu,
                     nstar = nstars[3],
                     alpha = 0.01)

# basic info
colorado.cepp1
# cluster info
summary(colorado.cepp1)
clusters(colorado.cepp1)


# basic info
colorado.cepp2
# cluster info
summary(colorado.cepp2)
clusters(colorado.cepp2)


# basic info
colorado.cepp3
# cluster info
summary(colorado.cepp3)
clusters(colorado.cepp3)

plot(sf::st_geometry(colorado), border = "grey60", axes = TRUE,
     col = color.clusters(colorado.cepp1))
legend("topright", legend = c("n* = 1"))
# basic plot
plot(colorado.cepp1)

plot(sf::st_geometry(colorado), border = "grey60", axes = TRUE,
     col = color.clusters(colorado.cepp2))
legend("topright", legend = c("n* = 2"))
# basic plot
plot(colorado.cepp2)

plot(sf::st_geometry(colorado), border = "grey60", axes = TRUE,
     col = color.clusters(colorado.cepp3))
legend("topright", legend = c("n* = 3"))
# basic plot
plot(colorado.cepp3)
```

# Spatial scan method

```{r}
# observed cases, rounded down
# cases <-  floor(denver$observed)
# # population (same as nydf$population)
# population <- denver$Adult_Popu
# # expected number of cases
# e <- sum(cases)/sum(population) * population
# # apply circular scan method
# denver.scan <- scan.test(coords = denver.coords,
#                  cases = cases,
#                  pop = population,
#                  ex = e,
#                  nsim = 999,
#                  alpha  = 0.10)
# save(denver.scan, file = 
#              "~../../Desktop/SpatialStatisticsClass/Project/denver_scan.rda")
load("~../../Desktop/SpatialStatisticsClass/Project/denver_scan.rda")


# results from the test are available in
summary(denver.scan)
# cluster information
clusters(denver.scan)

mycol = grDevices::hcl.colors(9)
# color.clusters(scan, col = mycol) colors the 3 clusters using the desired clusters
plot(sf::st_geometry(denver), border="grey60", axes=TRUE, main = "Denver Spatial Scan",
     col = color.clusters(denver.scan, col = mycol))
legend("topright", legend = c("Cluster A", "Cluster B", "Cluster C", 
                              "Cluster D", "Cluster E", "Cluster F",
                              "Cluster G", "Cluster H", "Cluster I"),
       lwd = 10, col = mycol)

# a simpler plot
plot(denver.scan, main = "Denver Spatial Scan")

```



```{r}
# observed cases, rounded down
# cases <-  floor(colorado$observed)
# # population (same as nydf$population)
# population <- colorado$Adult_Popu
# # expected number of cases
# e <- sum(cases)/sum(population) * population
# # apply circular scan method
# colorado.scan <- scan.test(coords = colorado.coords,
#                  cases = cases,
#                  pop = population,
#                  ex = e,
#                  nsim = 999,
#                  alpha  = 0.10)
# save(colorado.scan, file = 
#              "~../../Desktop/SpatialStatisticsClass/Project/colorado_scan.rda")
load("~../../Desktop/SpatialStatisticsClass/Project/colorado_scan.rda")


# results from the test are available in
summary(colorado.scan)
# cluster information
clusters(colorado.scan)

mycol = grDevices::hcl.colors(26)
# color.clusters(scan, col = mycol) colors the 3 clusters using the desired clusters
plot(sf::st_geometry(colorado), border="grey60", axes=TRUE, main = "Colorado Spatial Scan",
     col = color.clusters(colorado.scan, col = mycol))
legend("topright", legend = c("Cluster A", "Cluster B", "Cluster C", 
                              "Cluster D", "Cluster E", "Cluster F",
                              "Cluster G", "Cluster H", "Cluster I",
                              "Cluster J", "Cluster K", "Cluster L", 
                              "Cluster M", "Cluster N", "Cluster O",
                              "Cluster P", "Cluster Q", "Cluster R",
                              "Cluster S", "Cluster T", "Cluster U", 
                              "Cluster V", "Cluster W", "Cluster X",
                              "Cluster Y", "Cluster Z"),
       lwd = 10, col = mycol)

# a simpler plot
plot(colorado.scan, main = "Colorado Spatial Scan")

```

# Moran's I (constant risk version)

```{r}
N = length(colorado$observed) # number of regions
y = colorado$observed # number of cases
n = colorado$Adult_Popu #population sizes
r <- sum(y)/sum(n) # estimated risk
rni <- r * n # expected per region

w = nb2mat(colorado_nb, style = "B")
# see ?nb2listw for more options
# proximaty matrix in list format
lw = nb2listw(colorado_nb, style = "B")

nsim = 499
t0 = moran(y, listw = lw, n = N, S0 = Szero(lw))$I
# simulate data under CRH
tsim = numeric(nsim)
# calculate moran's i for poisson data simulated under crh
for (i in 1:nsim) {
  tsim[i] = moran(rpois(N, rni), listw = lw, n = N, S0 = Szero(lw))$I
}

# p-value for moran's i constant risk monte carlo test
(sum(tsim >= t0) + 1)/(nsim + 1)

```

# Geary's c

```{r}
t0 = geary(y, listw = lw, n = N, n1 = N - 1, S0 = Szero(lw))$C
# simulate data under CRH
tsim = numeric(nsim)
# calculate geary's c for poisson data simulated under crh
for (i in 1:nsim) {
  tsim[i] = geary(rpois(N, rni), listw = lw, n = N, n1 = N - 1, S0 = Szero(lw))$C
}

# p-value for geary's c constant risk monte carlo test
(sum(tsim <= t0) + 1)/(nsim + 1)
```


# Tango

```{r}
coords = as.matrix(colorado.coords)
cases = colorado$observed
pop = colorado$Adult_Popu

# Find distance matrix
d = as.matrix(dist(coords))

##################################################
# Exponential decay weight matrix
# use different kappas in defining weights
w1  <- dweights(coords, kappa = 1)
w7  <- dweights(coords, kappa = 7)
w10 <- dweights(coords, kappa = 10)
w15 <- dweights(coords, kappa = 15)
w20 <- dweights(coords, kappa = 20)

(tango_1  <- tango.test(cases, pop, w1))
(tango_7  <- tango.test(cases, pop, w7))
(tango_10 <- tango.test(cases, pop, w10))
(tango_15 <- tango.test(cases, pop, w15))
(tango_20 <- tango.test(cases, pop, w20))

gof <- c(tango_1$gof,tango_7$gof,
         tango_10$gof,tango_15$gof,
         tango_20$gof)
sa <- c(tango_1$sa,tango_7$sa,
        tango_10$sa,tango_15$sa,
        tango_20$sa)
plot(gof, sa)
```

```{r}
# Monte Carlo p-values

# compare monte carlo p-value to chi-square approximation p-value
# (tango_mc1 <-  tango.test(cases, pop, w1, nsim = 9999))
# save(tango_mc1, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc1.rda")
load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc1.rda")
tango_mc1
psim1 <- (1 + sum(tango_mc1$tstat.sim >= tango_mc1$tstat))/(1 + 9999)
print(paste("chi-square p: ", round(tango_1$pvalue.chisq,5),
            ", MC p: ",round(psim1, 5)))

# (tango_mc7 <-  tango.test(cases, pop, w7, nsim = 9999))
# save(tango_mc7, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc7.rda")
load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc7.rda")
psim7 <- (1 + sum(tango_mc7$tstat.sim >= tango_mc7$tstat))/(1 + 9999)
print(paste("chi-square p: ", round(tango_7$pvalue.chisq,5),
            ", MC p: ",round(psim7, 5)))

# (tango_mc10 <-  tango.test(cases, pop, w10, nsim = 9999))
# save(tango_mc10, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc10.rda")
load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc10.rda")
psim10 <- (1 + sum(tango_mc10$tstat.sim >= tango_mc10$tstat))/(1 + 9999)
print(paste("chi-square p: ", round(tango_10$pvalue.chisq,5),
            ", MC p: ",round(psim10, 5)))

# (tango_mc15 <-  tango.test(cases, pop, w15, nsim = 9999))
# save(tango_mc15, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc15.rda")
load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc15.rda")
psim15 <- (1 + sum(tango_mc15$tstat.sim >= tango_mc15$tstat))/(1 + 9999)
print(paste("chi-square p: ", round(tango_15$pvalue.chisq,5),
            ", MC p: ",round(psim15, 5)))

# (tango_mc20 <-  tango.test(cases, pop, w20, nsim = 9999))
# save(tango_mc20, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc20.rda")
load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tango_mc20.rda")
psim20 <- (1 + sum(tango_mc20$tstat.sim >= tango_mc20$tstat))/(1 + 9999)
print(paste("chi-square p: ", round(tango_20$pvalue.chisq,5),
            ", MC p: ",round(psim20, 5)))

# comparing gof and sa components of tango's index for the observed
# data to the simulated data
# x is observed
plot(tango_mc1)
# how extreme is each observed component
# compared to what we expect under the CRH
hist(tango_mc1$gof.sim, xlim = range(c(tango_mc1$gof.sim, tango_mc1$gof)))
abline(v = tango_mc1$gof)
hist(tango_mc1$sa.sim, xlim = range(c(tango_mc1$sa.sim, tango_mc1$sa)))
abline(v = tango_mc1$sa)
# change some of the default plotting options
plot(tango_mc7,
     obs.list = list(pch = 19, col = "purple"),
     sim.list = list(pch = ".", col = "grey"))
plot(tango_mc10)
plot(tango_mc15)
plot(tango_mc20)

```

## Rogerson Tango

```{r}
##################################################
# Exponential decay weight matrix
# use different kappas in defining weights
w1r  <- dweights(coords, kappa = 1, pop = pop, type = "rogerson")
w7r  <- dweights(coords, kappa = 7, pop = pop, type = "rogerson")
w10r <- dweights(coords, kappa = 10, pop = pop, type = "rogerson")
w15r <- dweights(coords, kappa = 15, pop = pop, type = "rogerson")
w20r <- dweights(coords, kappa = 20, pop = pop, type = "rogerson")

# Code to plot weights and "effective range"
# plotdist <- 0:max(d)
# kappa <- 10
# plot(plotdist,
#      exp(-plotdist/kappa),type="l",xlab="Distance",ylab="exp(-distance/kappa)",
#     cex.lab=1.5,cex.axis=1.25,ylim=c(0,1))
# #rug(dist)
# title(paste("kappa = ",kappa),cex.main=2.0)
# effrange <- -kappa*log(0.05)
# segments(0,0.05,effrange,0.05)
# segments(effrange,0,effrange,0.05)

###################################
# Calculate Tango's statistic

# the tango function takes the number of cases,
# the population, and the
# matrix of weights
(tango_1  <- tango.test(cases, pop, w1r))
(tango_7  <- tango.test(cases, pop, w7r))
(tango_10 <- tango.test(cases, pop, w10r))
(tango_15 <- tango.test(cases, pop, w15r))
(tango_20 <- tango.test(cases, pop, w20r))

# extracting goodness-of-fit and spatial autocorrelation
# components of tango's index
gof <- c(tango_1$gof,tango_7$gof,
         tango_10$gof,tango_15$gof,
         tango_20$gof)
sa <- c(tango_1$sa,tango_7$sa,
        tango_10$sa,tango_15$sa,
        tango_20$sa)
plot(gof, sa)
# gof stays the same since all sets of weights have w_{ii} =
# 1 the difference between value's of tango's index for
# different values of kappa derives entirely from
# differences in the spatial autocorrelation component
#
# changing wstar changes the skewness of tstat, which reduces
# the associated df for the chi-square approximation,
# resulting in much smaller p-values

###################################
# Monte Carlo p-values

# compare monte carlo p-value to chi-square approximation p-value
(tangor_mc1 <-  tango.test(cases, pop, w1r, nsim = 9999))
(tangor_mc7 <-  tango.test(cases, pop, w7r, nsim = 9999))
(tangor_mc10 <-  tango.test(cases, pop, w10r, nsim = 9999))
(tangro_mc15 <-  tango.test(cases, pop, w15r, nsim = 9999))
(tangor_mc20 <-  tango.test(cases, pop, w20r, nsim = 9999))

save(tangor_mc1, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc1.rda")
save(tangor_mc7, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc7.rda")
save(tangor_mc10, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc10.rda")
save(tangor_mc15, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc15.rda")
save(tangor_mc20, file = "~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc20.rda")

load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc1.rda")
load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc7.rda")
load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc15.rda")
load("~/../Desktop/SpatialStatisticsClass/Tango_MC/tangor_mc20.rda")


# comparing gof and sa components of tango's index for the observed
# data to the simulated data
# x is observed
plot(tangor_mc1)
plot(tangor_mc7)
plot(tangor_mc10)
plot(tangor_mc15)
plot(tangor_mc20)

```




